apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: artmr/hello:v2
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - nodePort: 38080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
  type: NodePort
